# This file was generated by GoReleaser. DO NOT EDIT.
cask "terragraph" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "20a03d1463fbe6a58da7bc8c6cffd92644856d3a1a6a2479a8b7d14ab5abe39c"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29a6167909429fb52cab98f61ae93770ccf78e429db31c5a0e4b2c4d7d2b65a3"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "abcf0859a8bd9ca94b752f97ceb2d869efe62114767d9b7b0bd52da5c9ae36db"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "64ea227d8ab1ef1eca703d1662fca8473d855802a7459251bc73872d29b0a924"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_x86_64.tar.gz"
    end
  end

  name "terragraph"
  desc "Graph-based orchestration for independent Terraform/OpenTofu root modules"
  homepage "https://github.com/cloudfluent/terragraph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terragraph"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  generate_completions_from_executable "terragraph",
    shell_parameter_format: :cobra

  # No zap stanza required
end
