# This file was generated by GoReleaser. DO NOT EDIT.
cask "terragraph" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "0d4a65a47259a7d57c96c18f52935658c1e1b432086fb07666f3ce1e790cc45f"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "72a6fc95185f7dbdcecd25908b3649487bc42679cdabc0cab577c6e9096cd604"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "faece94ffb31a873bac83edbe35ad6625775e9206523174ca19aaa95445081fa"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00f95b781990b4b377d5c6a487ac35c8dd4f8ee69a6749893a0670215edf8394"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_x86_64.tar.gz"
    end
  end

  name "terragraph"
  desc "Graph-based orchestration for independent Terraform/OpenTofu root modules"
  homepage "https://github.com/cloudfluent/terragraph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terragraph"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  generate_completions_from_executable "terragraph",
    shell_parameter_format: :cobra

  # No zap stanza required
end
