# This file was generated by GoReleaser. DO NOT EDIT.
cask "terragraph" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3abc54721ec33e034a8fd446a2ea5b85e288d1ac459c8d8db8c1cfce17430586"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "35ae22d61653b15eb35bcac081d786f1dbca2f339cbc523910a0fc4b42517b60"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e2a35948f1fe02c4f24cc6109ae1bd41926e30e7f90dcb449eaf8efc03b66e30"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8934582eb6e82f75212b455d78a6b9e1fdded1543509a6e213daf0f73dbee9e7"
      url "https://github.com/cloudfluent/terragraph/releases/download/v#{version}/terragraph_Linux_x86_64.tar.gz"
    end
  end

  name "terragraph"
  desc "Graph-based orchestration for independent Terraform/OpenTofu root modules"
  homepage "https://github.com/cloudfluent/terragraph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terragraph"

  generate_completions_from_executable "terragraph",
    shell_parameter_format: :cobra

  # No zap stanza required
end
